name: Verify
on: [push]

jobs:
#  linters:
#    name: Linters
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Ruby
#        uses: ruby/setup-ruby@v1
#      - name: Ruby gem cache
#        uses: actions/cache@v1
#        with:
#          path: vendor/bundle
#          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-gems-
#      - name: Install gems
#        run: |
#          bundle config path vendor/bundle
#          bundle install --jobs 4 --retry 3
#
#      - name: Run linters
#        run: |
#          bin/rubocop --parallel
#          bin/stylelint
#          bin/prettier
#          bin/eslint
#      - name: Run security checks
#        run: |
#          bin/brakeman -q -w2

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: commit-bridge-app
          POSTGRES_DB: commitbridgepostgres
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          gem install bundler -v 2.1.4
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: commit-bridge-app
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rspec
